name: ubiqmerchant_version_2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

#  Firebase Packages
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.6

  http: ^1.2.2

  awesome_notifications: ^0.10.0

  permission_handler: ^11.3.1

  flutter_bluetooth_printer: ^2.17.1
  url_launcher: ^6.3.1
  intl: ^0.19.0

  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  lottie: ^3.3.0

  flutter_echarts: ^2.5.0
  in_app_update: ^4.2.3

  google_places_flutter: ^2.0.9
  geocoding: ^3.0.0

#  State Management
  get: ^4.6.6

#  Icons Packages
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  flutter_animate: ^4.5.2
  get_storage: ^2.1.1
  flutter_otp_text_field: ^1.4.0+2
  connectivity_plus: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/images/animations/
